//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int authorid { get; set; }
        public string authorname { get; set; }
        public string authorsurname { get; set; }
        public string authorlastname { get; set; }
    }
}
